name: trivial_step2

on:
  workflow_run:
    workflows: [trivial_step1]
    types: [completed]

jobs:
  trivial_step2:
    runs-on: ubuntu-latest
    steps:
      - name: step1 run result conclusion
        run: |
          echo "From step 1 conclusion: ${{ github.event.workflow_run.conclusion }}"
      - name: step1 run result foo
        run: |
          echo "Blah: ${{ github.event.workflow_run }}"
          echo "Blah: ${{ toJSON(github.event.workflow_run) }}"
          echo "Blah: ${{ toJSON(github.event) }}"
      - name: trivial2
        run: |
          echo "Step 2: OK"
