name: trivial_step2

on:
  workflow_run:
    workflows: [trivial_step1]
    types: [completed]

jobs:
  trivial_step2:
    runs-on: ubuntu-latest
    steps:
      - name: step1 run result conclusion
        run: |
          echo "From step 1 conclusion: ${{ github.event.workflow_run.conclusion }}"
      - name: step1 run result foo
        run: |
          echo "Blah: ${{ github.event.workflow_run }}"
          echo "Blah: ${{ github.event.workflow_run.output.foo }}"
          echo "Blah: ${{ github.event.workflow_run.outputs.foo }}"
          echo "Blah: ${{ github.event.workflow_run.result.foo }}"
          echo "Blah: ${{ github.event.workflow_run.results.foo }}"
      - name: trivial2
        run: |
          echo "Step 2: OK"
