name: trivial_step1

on:
  push:
  workflow_dispatch:

jobs:
  trivial_step1:
    runs-on: ubuntu-latest
    steps:
      - name: set foo
        run: |
          echo "foo=$(echo $RANDOM)" >> $GITHUB_OUTPUT
      - name: trivial1
        run: |
          echo "Step 1 - OK"
